require("teemu-mjr.set")
require("teemu-mjr.packer")
require("teemu-mjr.nvim-tree")
require("teemu-mjr.remap")
require("teemu-mjr.bufferline")
require("teemu-mjr.comment")
require("teemu-mjr.toggleterm")
require("teemu-mjr.whichkey")
